### PR TITLE
Rename pipeline tests

### PR DESCRIPTION
**Pull request by maratdp**

### CODE REVIEW

**Comment by maratdp** [comment]
[TC_022.001 | Pipeline>Rename pipeline](https://trello.com/c/gakNipWJ/358-tc022001-pipelinerename-pipeline)

**Review by Rom-T — APPROVED** [review]

**Review by anonymoustuna — APPROVED** [review]

**Comment by maratdp** [comment]
[TC_022.004 | Pipeline>Rename pipeline with the same name](https://trello.com/c/xI8doWq1/507-tc022004-pipelinerename-pipeline-with-the-same-name)

**Comment by maratdp** [comment]
[TC_022.005 | Pipeline>Rename pipeline using unsupported characters](https://trello.com/c/mQrzXjYD/508-tc022005-pipelinerename-pipeline-using-unsupported-characters)

**Comment by maratdp** [comment]
[AT_022.001 | Pipeline>Rename pipeline with valid name](https://trello.com/c/j5zGpGaL/530-at022001-pipelinerename-pipeline-with-valid-name)

**Comment by maratdp** [comment]
[AT_022.004 | Pipeline>Rename pipeline with the same name](https://trello.com/c/htdxHkyC/531-at022004-pipelinerename-pipeline-with-the-same-name)

**Comment by maratdp** [comment]
[AT_022.005 | Pipeline>Rename pipeline using unsupported characters](https://trello.com/c/4F7opSST/532-at022005-pipelinerename-pipeline-using-unsupported-characters)

**Pull request merged**
