### PR TITLE
maratdp/freestyle project - build now

### PR DESCRIPTION
**Pull request by maratdp**

### CODE REVIEW

**Comment by maratdp** [comment]
[TC_006.001| Freestyle project > Build is appeared in different project pages](https://trello.com/c/1zqd6ffk/135-tc006001-freestyle-project-build-is-appeared-in-different-project-pages)

**Comment by maratdp** [comment]
[TC_006.002 | Freestyle project > Build is on the top of the build history](https://trello.com/c/WusfGdN1/136-tc006002-freestyle-project-build-is-on-the-top-of-the-build-history)

**Review by ke-de-ve — APPROVED** [review]

**Review by VitaliiArtemenko — APPROVED** [review]

**Comment by maratdp** [comment]
[TC_006.001| Freestyle project > Build is appeared in different project pages](https://trello.com/c/dFETVI2W/528-tc006001-freestyle-project-build-is-appeared-in-different-project-pages)

**Comment by maratdp** [comment]
[TC_006.002 | Freestyle project > Build is on the top of the build history](https://trello.com/c/1bDMjAMF/529-tc006002-freestyle-project-build-is-on-the-top-of-the-build-history)

**Pull request merged**
