### PR TITLE
AT_004.003| Freestyle project > Disable/Enable the project

### PR DESCRIPTION
**Pull request by patriotby07**

### CODE REVIEW

**Comment by patriotby07** [comment]
[AT_004.003| Freestyle project > Disable/Enable the project](https://trello.com/c/4t24aoCj/574-at004003-freestyle-project-disable-enable-the-project)

**Comment by MariaMoroz** [comment]
Согласно презентации "Работа с карточками в Трелло", пиар нужно называть именем карточки автомейшен, а именно : AT_004.003| Freestyle project > Disable/Enable the project

**Review by EugeniaSrednitskaya — APPROVED** [review]

**Review by RuslanG13 — APPROVED** [review]

**Comment by patriotby07** [comment]
[RF | <DisableEnableFreestyleProjectTest> testDisableEnableFreestyleProject and testDisableEnableIconsDashboard](https://trello.com/c/YJNFsHs1/579-rf-disableenablefreestyleprojecttest-testdisableenablefreestyleproject-and-testdisableenableiconsdashboard)

**Comment by patriotby07** [comment]
[AT_004.003| Freestyle project > Disable/Enable the project](https://trello.com/c/4t24aoCj/574-at004003-freestyle-project-disable-enable-the-project)

**Pull request merged**
