### PR TITLE
Lm/tc034 create organization folder

### PR DESCRIPTION
**Pull request by li-ma1**
tc034 create organization folder

### CODE REVIEW

**Comment by li-ma1** [comment]
[TC_034.001| New Item > Create Organization Folder](https://trello.com/c/3QSn4lxM/118-tc034001-new-item-create-organization-folder)

**Comment by li-ma1** [comment]
[TC_034.001| New Item > Create Organization Folder](https://trello.com/c/3QSn4lxM/118-tc034001-new-item-create-organization-folder)

**Comment by li-ma1** [comment]
[TC_034.001| New Item > Create Organization Folder](https://trello.com/c/3QSn4lxM/118-tc034001-new-item-create-organization-folder)

**Review by anonymoustuna — APPROVED** [review]
LGTM

**Comment by li-ma1** [comment]
[AT_034.001 | New Item > Create Organization Folder](https://trello.com/c/LKgZAV4h/159-at034001-new-item-create-organization-folder)

**Pull request merged**
