### PR TITLE
_MyViewTest > moved testAddDescriptionOnMyViews, testEditDescriptionO…

### PR DESCRIPTION
**Pull request by MarenaHolt**
_MyViewTest > moved testAddDescriptionOnMyViews, testEditDescriptionOnMyViews, testCheckButtonPreviewDescriptionOnMyViews, testCheckButtonHidePreviewDescriptionOnMyViews

Delite class FabrianaDescriptionOnMyViewsTests

### CODE REVIEW

**Review by RusAli — APPROVED** [review]

**Review by olpolezhaeva — APPROVED** [review]

**Comment by MarenaHolt** [comment]
[RF |_MyViewTest > moved testAddDescriptionOnMyViews](https://trello.com/c/G0sbOtLm/784-rf-myviewtest-moved-testadddescriptiononmyviews)

**Comment by MarenaHolt** [comment]
[RF |_MyViewTest > moved testCheckButtonHidePreviewDescriptionOnMyViews](https://trello.com/c/vSV3Gthf/787-rf-myviewtest-moved-testcheckbuttonhidepreviewdescriptiononmyviews)

**Comment by MarenaHolt** [comment]
[RF |_MyViewTest > moved testCheckButtonPreviewDescriptionOnMyViews](https://trello.com/c/7UaHd14j/786-rf-myviewtest-moved-testcheckbuttonpreviewdescriptiononmyviews)

**Comment by MarenaHolt** [comment]
[RF |_MyViewTest > moved testEditDescriptionOnMyViews()](https://trello.com/c/huy4mWQ5/785-rf-myviewtest-moved-testeditdescriptiononmyviews)

**Pull request merged**
