### PR TITLE
Refactoring _ManageUsersTest > testCheckValueInUsernameEqualValueFromFullName according to POM

### PR DESCRIPTION
**Pull request by ViktorPodgornov**
This test contained two asserts. The test was separated into two tests. The new test name is testCheckErrorMessagesIfFillOutOnlyUserNameField
https://trello.com/c/VIcxbnQQ/1059-at108005-create-user-page-user-can-see-error-messages-if-fill-out-only-user-name-field
Also, tests were refactored to POM

### CODE REVIEW

**Comment by ViktorPodgornov** [comment]
[RF |_ManageUsersTest > testCheckValueInUsernameEqualValueFromFullName](https://trello.com/c/HhEczz8D/1057-rf-manageuserstest-testcheckvalueinusernameequalvaluefromfullname)

**Comment by ViktorPodgornov** [comment]
[AT_108.001 | User can create a dddddddddddnew user](https://trello.com/c/VIcxbnQQ/1059-at108001-user-can-create-a-dddddddddddnew-user)

**Review by Stanislaw1349 — APPROVED** [review]
LGFM

**Comment by ViktorPodgornov** [comment]
[RF |_ManageUsersTest > testCheckValueInUsernameEqualValueFromFullName](https://trello.com/c/HhEczz8D/1057-rf-manageuserstest-testcheckvalueinusernameequalvaluefromfullname)

**Comment by ViktorPodgornov** [comment]
[AT_108.005 | Create User Page | User can see error messages if fill out only user name field](https://trello.com/c/VIcxbnQQ/1059-at108005-create-user-page-user-can-see-error-messages-if-fill-out-only-user-name-field)

**Review by DVRudoi — APPROVED** [review]

**Pull request merged**
