### PR TITLE
Added some fields, methods, tests, and dependency (dependsOnMethods, priority)

### PR DESCRIPTION
**Pull request by ViktorPodgornov**
Created PASSWORD, EMAIL fields

Created userName, passwordOne, passwordTwo, fullName, email, createUserButtonSubmit, urlPageCreateUser, fillOutFieldsCreateUser methods

Added testUserNameFieldIsDisplayed, testPasswordTwoFieldIsDisplayed, testFullNameFieldIsDisplayed, testEmailFieldIsDisplayed, estCreateUserButtonSubmitIsDisplayed, testUsernameFieldDoesNotAcceptSpecialCharacters

Added dependsOnMethods and set priority

### CODE REVIEW

**Comment by ViktorPodgornov** [comment]
[TC_108.001 | Create User Page | User can see input Username field](https://trello.com/c/xxRgDkXW/292-tc108001-create-user-page-user-can-see-input-username-field)

**Comment by ViktorPodgornov** [comment]
[TC_108.002 | Create User Page | User can see input Password field](https://trello.com/c/Zu7YnzYK/295-tc108003-create-user-page-user-can-see-input-password-field)

**Comment by ViktorPodgornov** [comment]
[TC_108.002 | Create User Page | User can see input Password field](https://trello.com/c/Zu7YnzYK/295-tc108003-create-user-page-user-can-see-input-password-field)

**Comment by ViktorPodgornov** [comment]
[TC_108.003 | Create User Page | User can see input Confirm password field](https://trello.com/c/r3ONYeLQ/294-tc108001-create-user-page-user-can-see-input-password-field)

**Comment by ViktorPodgornov** [comment]
[TC_108.003 | Create User Page | User can see input Confirm password field](https://trello.com/c/r3ONYeLQ/294-tc108001-create-user-page-user-can-see-input-password-field)

**Comment by ViktorPodgornov** [comment]
[TC_108.004 | Create User Page | User can see input Full name field](https://trello.com/c/ai3S0TP4/296-tc108004-create-user-page-user-can-see-input-full-name-field)

**Comment by ViktorPodgornov** [comment]
[TC_108.005 | Create User Page | User can see input E-mail address field](https://trello.com/c/Xtuy8Yo3/297-tc108004-create-user-page-user-can-see-input-e-mail-address-field)

**Comment by ViktorPodgornov** [comment]
[TC_108.006 | Create User Page | User can see Create User button](https://trello.com/c/L9nOSFwO/298-tc108005-create-user-page-user-can-see-create-user-button)

**Comment by ViktorPodgornov** [comment]
[TC_108.009 | Create User Page | Username field does not accept special characters](https://trello.com/c/cvK9E8MX/299-tc108009-create-user-page-username-field-does-not-accept-special-characters)

**Comment by ViktorPodgornov** [comment]
[TC_108.009 | Create User Page | Username field does not accept special characters](https://trello.com/c/cvK9E8MX/299-tc108009-create-user-page-username-field-does-not-accept-special-characters)

**Review by anonymoustuna — APPROVED** [review]

**Review by Stanislaw1349 — APPROVED** [review]

**Review by SafronovaOlga — APPROVED** [review]

**Comment by ViktorPodgornov** [comment]
[AT_108.001 | Create User Page | User can see input Username field](https://trello.com/c/Sa39hGjM/458-at108001-create-user-page-user-can-see-input-username-field)

**Comment by ViktorPodgornov** [comment]
[AT_108.009 | Create User Page | Username field does not accept special characters](https://trello.com/c/AqotWYjy/468-at108009-create-user-page-username-field-does-not-accept-special-characters)

**Pull request merged**
