### PR TITLE
RF | <_ManageUsersTest & ManageUsersEditUserTest> testEditUserFullName

### PR DESCRIPTION
**Pull request by ViktorPodgornov**
Move testEditUserName from the ManageUsersEditUserTest class to the _ManageUsersTest class and remove the ManageUsersEditUserTest class

### CODE REVIEW

**Comment by ViktorPodgornov** [comment]
[RF | <_ManageUsersTest & ManageUsersEditUserTest> testEditUserFullName](https://trello.com/c/iIeO9nYw/700-rf-manageuserstest-manageuserseditusertest-testedituserfullname)

**Review by anonymoustuna — APPROVED** [review]

**Review by RusAli — APPROVED** [review]

**Comment by ViktorPodgornov** [comment]
[ERR | CreateNewViewWithSelectLabelMyViewTest > deleteCreatedView](https://trello.com/c/QbAyaa6P/723-err-createnewviewwithselectlabelmyviewtest-deletecreatedview)

**Comment by ViktorPodgornov** [comment]
[ERR | EditViewChangeNameTest > testEditView_TC_027_001 | deleteCreatedView](https://trello.com/c/B7HuzvHL/725-err-editviewchangenametest-testeditviewtc027001-deletecreatedview)

**Comment by ViktorPodgornov** [comment]
[ERR | PipelineCheckHelpIconTest > testCheckHelpIcon | testCheckHelpIconNoText | testCheckHelpIconText](https://trello.com/c/1fpwPgb9/726-err-pipelinecheckhelpicontest-testcheckhelpicon-testcheckhelpiconnotext-testcheckhelpicontext)

**Comment by ViktorPodgornov** [comment]
[ERR | DisableEnableFreestyleProjectTest > testDeleteAllProject](https://trello.com/c/QtdUIPPN/728-err-disableenablefreestyleprojecttest-testdeleteallproject)

**Comment by ViktorPodgornov** [comment]
[ERR | _MultibranchPipelineTest > testScanResult](https://trello.com/c/1EPi7r9F/727-err-multibranchpipelinetest-testscanresult)

**Comment by ViktorPodgornov** [comment]
[ERR | _MultibranchPipelineTest > testScanResult](https://trello.com/c/1EPi7r9F/727-err-multibranchpipelinetest-testscanresult)

**Comment by ViktorPodgornov** [comment]
[ERR | _MultibranchPipelineTest > testScanResult](https://trello.com/c/1EPi7r9F/727-err-multibranchpipelinetest-testscanresult)

**Pull request merged**
