### PR TITLE
RF | _PipelineTest > refactoring tests under POM

### PR DESCRIPTION
**Pull request by patriotby07**

### CODE REVIEW

**Review by hronorog — APPROVED** [review]

**Comment by patriotby07** [comment]
[RF | _PipelineTest > refactoring tests under POM](https://trello.com/c/KB7Yex7e/1011-rf-pipelinetest-refactoring-tests-under-pom)

**Comment by patriotby07** [comment]
[RF | BuildHistoryPage> create BuildHistoryPage and add POM](https://trello.com/c/oqD3S7QL/1013-rf-buildhistorypage-create-buildhistorypage-and-add-pom)

**Comment by patriotby07** [comment]
[RF | HomePage> add POM](https://trello.com/c/2C7WJJEm/1015-rf-homepage-add-pom)

**Comment by patriotby07** [comment]
[RF | PipelineConfigPage> add POM](https://trello.com/c/QoLOgAHP/1016-rf-pipelineconfigpage-add-pom)

**Comment by patriotby07** [comment]
[ERR | _PipelineTest > testCheckScheduledBuildInBuildHistory](https://trello.com/c/fLqE1fCG/968-err-pipelinetest-testcheckscheduledbuildinbuildhistory)

**Review by RuslanG13 — APPROVED** [review]

**Pull request merged**
