### PR TITLE
RF | _MyViewTest > tests to Create, Edit, Delete View to chain

### PR DESCRIPTION
**Pull request by olpolezhaeva**
Changed testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs, testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs, testCreateNewViewWithSelectLabelListViewCheckTabBar, testCreateNewViewWithSelectLabelMyViewCheckTabBar, testCreateNewViewWithAnExistingName, testEditViewChangeName, testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame to POM.

### CODE REVIEW

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Comment by olpolezhaeva** [comment]
[RF | _MyViewTest > testCreateNewViewWithSelectLabelListViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelMyViewCheckBreadcrumbs | testCreateNewViewWithSelectLabelListViewCheckTabBar | testCreateNewViewWithSelectLabelMyViewCheckTabBar | testCreateNewViewWithAnExistingName, testEditViewChangeName | testDeleteViewViaBreadcrumbs, testDeleteViewViaTabBarFrame](https://trello.com/c/8ODWN4OO/1000-rf-myviewtest-testcreatenewviewwithselectlabellistviewcheckbreadcrumbs-testcreatenewviewwithselectlabelmyviewcheckbreadcrumbs-te)

**Review by marolespb8 — APPROVED** [review]

**Review by ValeriiSarukhanov — APPROVED** [review]

**Pull request merged**
