### PR TITLE
TC_034.008 | New Item > Create Organization Folder Navigation test, TC_034.009 | New Item > Create Organization Folder with Display name

### PR DESCRIPTION
**Pull request by DariaKozh**

### CODE REVIEW

**Comment by DariaKozh** [comment]
https://trello.com/c/7ZHbSeKa/452-at034008-new-item-create-organization-folder-navigation-test
https://trello.com/c/3s7wpqR9/453-at034009-new-item-create-organization-folder-with-display-name

**Comment by DariaKozh** [comment]
[ERR | Pipeline > Build Pipeline with parameters](https://trello.com/c/QYAxzYn0/455-err-pipeline-build-pipeline-with-parameters)

**Comment by DariaKozh** [comment]
[AT_034.008 | New Item > Create Organization Folder Navigation test](https://trello.com/c/7ZHbSeKa/452-at034008-new-item-create-organization-folder-navigation-test)

**Comment by DariaKozh** [comment]
[AT_034.009 | New Item > Create Organization Folder with Display name](https://trello.com/c/3s7wpqR9/453-at034009-new-item-create-organization-folder-with-display-name)

**Review by jbioshock1912 — APPROVED** [review]

**Pull request merged**
