### PR TITLE
TC_030.001 & TC_031.001 | Build History > Changes & Console Output

### PR DESCRIPTION
**Pull request by azellus-tercia**
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0kBm92hN&#x2F;143-tc030001-build-history-changes">TC_030.001 | Build History &gt; Changes</a></blockquote>

Also added test for TC_031.001 | Build History > Console Output
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7fIeFgyB&#x2F;154-tc031001-build-history-console-output">TC_031.001 | Build History &gt; Console Output</a></blockquote>

### CODE REVIEW

**Comment by azellus-tercia** [comment]
[TC_030.001 | Build History > Changes](https://trello.com/c/veq74585/255-tc030001-build-history-changes)

**Comment by azellus-tercia** [comment]
[TC_031.001 | Build History > Console Output](https://trello.com/c/eXXnb7Vs/256-tc031001-build-history-console-output)

**Comment by azellus-tercia** [comment]
[TC_030.001 & TC_031.001 | Build History > Changes & Console Output](https://trello.com/c/veq74585/255-tc030001-tc031001-build-history-changes-console-output)

**Review by SafronovaOlga — APPROVED** [review]

**Review by anonymoustuna — APPROVED** [review]
LGTM

**Pull request merged**
