### PR TITLE
RF | AT | Multi-configuration project

### PR DESCRIPTION
**Pull request by val-kan**
Refactor and add new tests:
AT_041.007 | New Item > Create Multi-configuration project
https://trello.com/c/mSLSCvCw

AT_042.001 | Multi-configuration project > add description
https://trello.com/c/KVtzyUex

AT_045.003 | Multi-configuration project > Disable project
https://trello.com/c/GuVtTtwZ

AT_046.002 | Multi-configuration project > delete project
https://trello.com/c/GcnOxfoe

AT_044.002 | Multi-configuration project > build now
https://trello.com/c/eaYVQie2

AT_043.007 | Multi-configuration project > rename
https://trello.com/c/AsjS99P1

### CODE REVIEW

**Comment by val-kan** [comment]
[AT_041.007 | New Item > Create Multi-configuration project](https://trello.com/c/mSLSCvCw/617-at041007-new-item-create-multi-configuration-project)

**Comment by val-kan** [comment]
[AT_045.003 | Multi-configuration project > Disable project](https://trello.com/c/GuVtTtwZ/618-at045003-multi-configuration-project-disable-project)

**Comment by val-kan** [comment]
[AT_046.002 | Multi-configuration project > delete project](https://trello.com/c/GcnOxfoe/619-at046002-multi-configuration-project-delete-project)

**Comment by val-kan** [comment]
[AT_044.002 | Multi-configuration project > build now](https://trello.com/c/eaYVQie2/620-at044002-multi-configuration-project-build-now)

**Comment by val-kan** [comment]
[AT_043.007 | Multi-configuration project > rename](https://trello.com/c/AsjS99P1/621-at043007-multi-configuration-project-rename)

**Comment by val-kan** [comment]
[AT_042.001 | Multi-configuration project > add description](https://trello.com/c/KVtzyUex/293-at042001-multi-configuration-project-add-description)

**Review by belht — APPROVED** [review]

**Review by Stanislaw1349 — APPROVED** [review]

**Pull request merged**
