### PR TITLE
RF | _PipelineTest > refactoring testBuildPipelineWithParameters for POM and delete methods and constants

### PR DESCRIPTION
**Pull request by patriotby07**
https://trello.com/c/AcUepyPW/1092-rf-pipelinetest-refactoring-testbuildpipelinewithparameters-for-pom-and-delete-methods-and-constants
https://trello.com/c/l1lgN9EG/1093-rf-buildparameterspage-create-buildparameterspage-and-add-pom
https://trello.com/c/qxyrPs7g/1094-rf-buildwithparameterspage-add-pom
https://trello.com/c/Xg79qlOW/1095-rf-projectpage-add-pom

### CODE REVIEW

**Comment by patriotby07** [comment]
[RF | _PipelineTest > refactoring testBuildPipelineWithParameters for POM and delete methods and constants](https://trello.com/c/AcUepyPW/1092-rf-pipelinetest-refactoring-testbuildpipelinewithparameters-for-pom-and-delete-methods-and-constants)

**Comment by patriotby07** [comment]
[RF | BuildParametersPage> create BuildParametersPage and add POM](https://trello.com/c/l1lgN9EG/1093-rf-buildparameterspage-create-buildparameterspage-and-add-pom)

**Comment by patriotby07** [comment]
[RF | BuildWithParametersPage> add POM](https://trello.com/c/qxyrPs7g/1094-rf-buildwithparameterspage-add-pom)

**Comment by patriotby07** [comment]
[RF | ProjectPage> add POM](https://trello.com/c/Xg79qlOW/1095-rf-projectpage-add-pom)

**Review by RuslanG13 — APPROVED** [review]

**Review by korelov — APPROVED** [review]

**Pull request merged**
