### PR TITLE
Refactoring _ManageUsersTest > testCreateUserEmptyFields according to POM

### PR DESCRIPTION
**Pull request by ViktorPodgornov**
After the first approval, added changes - details in the card: https://trello.com/c/B9PeopPf/1050-rf-manageuserstest-createuserpage-added-generics

### CODE REVIEW

**Comment by ViktorPodgornov** [comment]
[RF |_ManageUsersTest > testErrorMessagesHaveValidCssValues](https://trello.com/c/3rJBix1s/1047-rf-manageuserstest-testerrormessageshavevalidcssvalues)

**Comment by ViktorPodgornov** [comment]
[RF |_ManageUsersTest > testCreateUserEmptyFields according to POM](https://trello.com/c/hOEgwbhe/1049-rf-manageuserstest-testcreateuseremptyfields-according-to-pom)

**Comment by ViktorPodgornov** [comment]
[RF |_ManageUsersTest > testCreateUserEmptyFields](https://trello.com/c/hOEgwbhe/1049-rf-manageuserstest-testcreateuseremptyfields)

**Review by dmswlpk — APPROVED** [review]

**Comment by ViktorPodgornov** [comment]
[RF |_ManageUsersTest & CreateUserPage added generics](https://trello.com/c/B9PeopPf/1050-rf-manageuserstest-createuserpage-added-generics)

**Review by ksutitova — APPROVED** [review]

**Pull request merged**
