### PR TITLE
Added test <testUserCanDeleteUser>

### PR DESCRIPTION
**Pull request by ViktorPodgornov**

### CODE REVIEW

**Comment by ViktorPodgornov** [comment]
[TC_108.002 | User can delete user](https://trello.com/c/FiO6X8WC/102-tc108002-user-can-delete-user)

**Comment by ViktorPodgornov** [comment]
[TC_108.002 | User can delete user](https://trello.com/c/FiO6X8WC/102-tc108002-user-can-delete-user)

**Comment by ViktorPodgornov** [comment]
[TC_108.002 | User can delete user](https://trello.com/c/FiO6X8WC/102-tc108002-user-can-delete-user)

**Comment by ViktorPodgornov** [comment]
[TC_108.002 | User can delete user](https://trello.com/c/FiO6X8WC/102-tc108002-user-can-delete-user)

**Review by GettingPro — APPROVED** [review]

**Review by RusAli — APPROVED** [review]

**Comment by ViktorPodgornov** [comment]
[AT_108.008 | User can delete user](https://trello.com/c/GhWJQj83/467-at108008-user-can-delete-user)

**Pull request merged**
