### PR TITLE
 _ManageJenkinsTest > add new tests for checking items captions

### PR DESCRIPTION
**Pull request by misssEvil**
_ManageJenkinsTest > add new tests for checking items captions

https://trello.com/c/X370qAc8/1224-at139005-managejenkinstest-check-items-captions-section-system-configuration
https://trello.com/c/h2kGgogy/1232-at139006-managejenkinstest-check-item-captions-section-security
https://trello.com/c/Oh1FkiQu/1235-at139007-managejenkinstest-check-item-captions-section-status-information

### CODE REVIEW

**Comment by misssEvil** [comment]
[AT_139.005 | _ManageJenkinsTest > check items captions](https://trello.com/c/X370qAc8/1224-at139005-managejenkinstest-check-items-captions)

**Comment by misssEvil** [comment]
[AT_139.006 | _ManageJenkinsTest > check item captions (section "Security")](https://trello.com/c/h2kGgogy/1232-at139006-managejenkinstest-check-item-captions-section-security)

**Comment by misssEvil** [comment]
[AT_139.006 | _ManageJenkinsTest > check item captions (section "Security")](https://trello.com/c/h2kGgogy/1232-at139006-managejenkinstest-check-item-captions-section-security)

**Comment by misssEvil** [comment]
[AT_139.007 | _ManageJenkinsTest > check item captions (section "Status Information")](https://trello.com/c/Oh1FkiQu/1235-at139007-managejenkinstest-check-item-captions-section-status-information)

**Review by EugeniaSrednitskaya — APPROVED** [review]

**Review by SvetlanaG1011 — APPROVED** [review]

**Comment by Stanislaw1349** [comment]
RP no movement 13 days

**Pull request closed without merging**
